#!/bin/bash
#
# Execute command. Use gash-log to write status information
# to stderr and supress output of command itself.

#######################################
# Write usage info to stderr and exit
# with 1.
# Outputs:
#  Usage info and help hint
#######################################
function info_and_exit() {
	echo -e "Usage: $USAGE"
	echo -e "       $HINT"
	exit 1
}

##
## Constants
##
readonly NAME="$(basename $0)"
readonly VERSION="0.1"
readonly USAGE="$NAME [options] COMMAND MESSAGE"
readonly HINT="-h for help"

readonly DESCRIPTION=$( cat << description
Execute command. Use gash-log to write status information
to stderr and supress output of command itself.
description
)

readonly ARGUMENTS=$( cat << arguments
\tCOMMAND ............... Command to be executed.
\tMESSAGE ............... Description of what COMMAND is doing.
arguments
)

readonly OPTIONS=$( cat << options
\t-l (level) LEVEL ...... Message level used for gash-log
\t                        (default: ´INFO´).
\t-v (verbose) .......... More output.
\t-d (dry-run) .......... Do not actually execute.
\t-c (color) ............ Produce colored output.
\t-t (timestamp) ........ Include timestamp in output.
\t-V (version) .......... Print version and exit.
\t-h (help) ............. Print help and exit.
options
)

readonly ENVIROMENT_VARIABLES=$( cat << enviroment_variables
\tGASHOPT_TIMESTAMP ..... true|false (default: false)
\t                        Include iso 8601 timestamp in output. Can be
\t                        overwritten by ´-t´ option.
\tGASHOPT_COLOR ......... true|false (default: false)
\t                        Produce colored output. Can be overwritten
\t                        by ´-c´ option.
\tGASHOPT_DRYRUN ........ true|false (default: false)
\t                        Don't execute given command. Can be
\t                        overwritten by ´-d´ option.
\tGASHOPT_VERBOSE ....... true|false (default: false)
\t                        Produce more output. Can be overwritten by
\t                        ´-v´ option.
enviroment_variables
)

readonly HELP=$( cat << help
$NAME/v$VERSION

$DESCRIPTION

Usage:
\t$USAGE

Arguments:
$ARGUMENTS

Options:
$OPTIONS

Enviroment variables:
$ENVIROMENT_VARIABLES
help
)

##
## Enviroment variables & defaults
##
[[ -z "$GASHOPT_TIMESTAMP" ]] && GASHOPT_TIMESTAMP=false
[[ -z "$GASHOPT_COLOR" ]] && GASHOPT_COLOR=false
[[ -z "$GASHOPT_DRYRUN" ]] && GASHOPT_DRYRUN=false
[[ -z "$GASHOPT_VERBOSE" ]] && GASHOPT_VERBOSE=false
MESSAGE_LEVEL="INFO"

##
## Options
##
while getopts "l:vdctVh" opt; do
	case "$opt" in
		l)
			readonly MESSAGE_LEVEL="$OPTARG"
			;;
		v)
			readonly GASHOPT_VERBOSE=true
			;;
		d)
			readonly GASHOPT_DRYRUN=true
			;;
		c)
			export GASHOPT_COLOR=true
			;;
		t)
			export GASHOPT_TIMESTAMP=true
			;;
		V)
			echo -e "$VERSION"
			exit 0
			;;
		h)
			echo -e "$HELP"
			exit 0
			;;
		*)
			info_and_exit
			;;
	esac
done

# Remove options from $@
shift $((OPTIND-1))

##
## Arguments
##
if [[ $# -ne 2 ]]; then
	echo -e "$0: Wrong number of arguments." 1>&2
	info_and_exit
fi

readonly COMMAND="$1"
readonly MESSAGE="$2"

##
## Color
##
if $GASHOPT_COLOR; then
	readonly RED="\e[1m\e[91m" # Bold + Light red
	readonly GREEN="\e[1m\e[92m" # Bold + Light green
	readonly YELLOW="\e[1m\e[93m" # Bold + Light yellow
	readonly CYAN="\e[96m" # Light cyan
	readonly MAGENTA="\e[95m" # Light magenta
	readonly RESET="\e[39m\e[0m"
else
	readonly RED=""
	readonly GREEN=""
	readonly YELLOW=""
	readonly CYAN=""
	readonly MAGENTA=""
	readonly RESET=""
fi

##
## Output
##
gash-log -o "-en" "$MESSAGE_LEVEL" "$MESSAGE... " 1>&2

if $GASHOPT_VERBOSE ; then
	gash-log -s "$MESSAGE_LEVEL" "\n$CYAN>>> $MAGENTA$COMMAND$RESET" 1>&2
fi

##
## Execution
##
if $GASHOPT_DRYRUN; then
	RESULT=0
else
	OUTPUT="$($COMMAND 2>&1)"
	RESULT=$?
fi

##
## Result
##
if $GASHOPT_VERBOSE; then
	gash-log -s "$MESSAGE_LEVEL" "$OUTPUT" 1>&2
	gash-log -s -o "-en" "$MESSAGE_LEVEL" "$CYAN<<<$RESET " 1>&2
fi

if $GASHOPT_DRYRUN; then
	gash-log -s "$MESSAGE_LEVEL" "$YELLOW(Dry run)$RESET" 1>&2
elif [[ $RESULT -eq 0 ]]; then
	gash-log -s "$MESSAGE_LEVEL" "$GREEN(Ok)$RESET" 1>&2
else
	gash-log -s "$MESSAGE_LEVEL" "$RED(Failed)$RESET" 1>&2
fi

##
## Done
##
exit $RESULT
