#!/bin/bash
#
# Write timestamped copy of a file. And/or remove
# already exsiting copies.

#######################################
# Write usage info to stderr and exit
# with 1.
#
# Outputs:
#  Usage info and help hint
#######################################
function info_and_exit() {
	echo -e "Usage: $USAGE" 1>&2
	echo -e "       $HINT" 1>&2
	exit 1
}

#######################################
# Prompt for user conformation. Exit
# with 0, unless input is y or yes.
# Will be skipped if `-f` option is
# active.
#
# Parameters:
#  $1 (return_value) Value exit will
#     return with if user dosen't
#     confirm (default: `0`).
# Outputs:
#  Prompt message
#  or nothing if `-f` is active
#######################################
function ask_for_continue() {
	if ! $FORCE; then
		read -r -p "Do you want to continue? [y/N] " response
		case "$response" in
			[yY][eE][sS]|[yY])
				;;
			*)
				[[ -z "$1" ]] && return_value=0
				exit $return_value
				;;
		esac
	fi
}

#######################################
# Count number of copies determined by
# target path. Remove the oldest ones
# if they exceed the provided limit.
#
# Parameters:
#   $1 (targets) path to copies that
#      will be counted and possibly
#      removed
#   $2 (limit) maximum number of coipes
#      that will be kept
# Outputs:
#   Several messages with execution
#   details, depending on 
#   GASHOPT_LOGLEVEL
#######################################
function remove() {
	if [[ $2 -eq 0 ]]; then
		gash-echo "DEBUG" "Skipped..."
	else
		targets=($1)
		count=${#targets[@]}
		difference="$(($count-$2))"
		gash-echo "DEBUG" "Copies found: $count ($RETAINED retained from previous step); Copies to be deleted: $difference"
		if [[ $RETAINED -ne 0 && $difference -gt "$(($count-$RETAINED))" ]]; then
			gash-echo "WARN" "Copies retained from a previous step will be removed."
			ask_for_continue
		fi
		if [[ $count -gt 0 && $difference -gt 0 ]]; then
			i=0
			rmlist=""
			for target in $1; do
				if [[ $i -lt $difference ]]; then
					rmlist="$rmlist $target"
				else
					break
				fi
				let i++
			done
			gash-exec "rm $OPTS $rmlist" "Removing $difference copies of '$FILENAMEFULL'"
			if [[ $? -ne 0 ]]; then
				gash-echo "ERROR" "Failed to remove copies of '$FILENAMEFULL'"
				RETURN_VALUE=1
				ask_for_continue 1
			fi
			RETAINED="$(($count-$difference))"
		else
			RETAINED=$count
		fi
	fi
}

#######################################
#
#######################################
function count() {
	targets=$(gash-exec -l "DEBUG" -o "ls -d $1" "Looking for copies")
	if [[ $? -ne 0 ]]; then
		echo 0
	else
		echo $targets | wc -w
	fi
}

##
## Constants
##
readonly NAME="$(basename $0)"
readonly VERSION="1.0"
readonly USAGE="$NAME [options] [command] FILE"
readonly HINT="-h for help"

readonly DESCRIPTION=$( cat << description
Write timestamped copy of a file. And/or remove already existing
copies.
description
)

readonly ARGUMENTS=$( cat << arguments
\tCOMMAND .... Command to be executed (default: ´copy´).
\t               copy|cp .......... Write timestamped copy of
\t                                  FILE.
\t               remove|rm......... Remove old copies of FILE.
\t               copyremove|cprm .. Copy, then remove.
\t               list|ls .......... List existing copies.
\t               stats|st ......... Count existing copies.
\tFILE ....... Path to file you want to rotate.
arguments
)

readonly OPTIONS=$( cat << options
\t-p (path) PATH ....... Path to destination directory where
\t                       copies will be written/removed
\t                       (default: ´./´).
\t-m (mode) D.M.Y.A .... Retention mode for remove, more info
\t                       below (default: ´0.0.0.64´).
\t-f (force) ........... Never prompt. Apply force to cp and
\t                       rm commands.
\t-r (recursive) ....... Apply recursive to cp and rm
\t                       commands.
\t-v (verbose) ......... More output.
\t-D (debug) ........... Include debug messages in output.
\t-d (dry-run) ......... Do not actually execute commands.
\t-c (color) ........... Use color in output.
\t-V (version) ......... Print version and exit.
\t-h (help) ............ Print help and exit.
options
)

readonly RETENTIONMODE=$(cat << retentionmode
\tBehaviour of the remove command is determined by the choosen
\tretention mode, defined by four numbers combined by dots:
\t
\tDAY.MONTH.YEAR.ALL
\t
\tDAY ...... In it's first step, the remove command will check if
\t           the number of timestamped copies of FILE written
\t           today exeeds the number given here. If so, it will
\t           delete the oldest copies until the number matches.
\t           To skip this step choose ´0´.
\tMONTH .... In it's second step, the remove command will check if
\t           the number of timestamped copies (*including* those
\t           written today) exeeds this number and delete the
\t           the oldest ones if neccessary. To skip this step
\t           choose ´0´.
\tYEAR ..... In it's thitd step, remove will count all timesptamped
\t           copies written this year (*inluding* this month and
\t           today) and delete the oldest ones if neccessary. To 
\t           skip this step choose ´0´.
\tALL ...... In it's final step, remove will count all excisting
\t           timestamped copies (regardless when they where
\t           written) and delete the oldest ones, if they exeed
\t           this number. To skip this step choose ´0´.
\t
\tExamples:
\t  0.0.0.64 .... Just keep up to 64 copies, regardless of their
\t                timestamps. This is the default.
\t  2.4.8.0 ..... If more than two copies with todays timestamp
\t                  exist: Remove the oldest ones until only two
\t                  remain.
\t                If more than four copies with this months timestamp
\t                  exist (including the up to two from today):
\t                  Remove the oldest ones until only four remain.
\t                If more than eight copies with this years timestamp
\t                  exist (including those from this month and today):
\t                  Remove the oldest ones until only eight remain.
\t                Do not delete any copies from previous years.
retentionmode
)

readonly ENVIROMENT_VARIABLES=$( cat << enviroment_variables
\tGASHOPT_TIMESTAMP ..... true|false (default: false)
\t                        Include iso 8601 timestamp in output lines.
\t                        Can be overwritten by ´-t´ option.
\tGASHOPT_COLOR ......... true|false (default: false)
\t                        Use color in output. Can be overwritten by
\t                        ´-c´ option.
\tGASHOPT_DRYRUN ........ true|false (default: false)
\t                        Don't execute commands. Can be overwritten by
\t                        ´-d´ option.
\tGASHOPT_VERBOSE ....... true|false (default: false)
\t                        More output. Can be overwritten by ´-v´
\t                        option.
\tGASHOPT_LOGLEVEL ...... ERROR|WARN|INFO|DEBUG (detault: INFO)
\t                        Only messages with at least the choosen level
\t                        will be written to output. Can be overwritten
\t                        by ´-D´ option.
\tGASHOPT_GR_PATH ....... PATH (default: ./)
\t                        Path where copies of FILE will be written or
\t                        removed. Can be overwritten by ´-p´ option.
\tGASHOPT_GR_MODE ....... Num.Num.Num.Num (default: 0.0.0.64)
\t                        Retention mode for remove. Can be overwritten
\t                        by ´-m´ option.
enviroment_variables
)

readonly HELP=$( cat << help
$NAME/v$VERSION

$DESCRIPTION

Usage:
\t$USAGE

Arguments:
$ARGUMENTS

Options:
$OPTIONS

Retention mode:
$RETENTIONMODE

Enviroment variables:
$ENVIROMENT_VARIABLES
help
)

##
## Enviroment variables & defaults
##
[[ -z "$GASHOPT_TIMESTAMP" ]] && export GASHOPT_TIMESTAMP=false
[[ -z "$GASHOPT_COLOR" ]] && export GASHOPT_COLOR=false
[[ -z "$GASHOPT_DRYRUN" ]] && export GASHOPT_DRYRUN=false
[[ -z "$GASHOPT_VERBOSE" ]] && export GASHOPT_VERBOSE=false
[[ -z "$GASHOPT_LOGLEVEL" ]] && export GASHOPT_LOGLEVEL="INFO"
[[ -z "$GASHOPT_GR_PATH" ]] && export GASHOPT_GR_PATH="./"
[[ -z "$GASHOPT_GR_MODE" ]] && export GASHOPT_GR_MODE="0.0.0.64"
FORCE=false
OPTS="-v"
RETURN_VALUE=0

##
## Options
##
while getopts "p:m:frvDdctVh" opt; do
	case "$opt" in
		p)
			export GASHOPT_GR_PATH="$OPTARG"
			;;
		m)
			export GASHOPT_GR_MODE="$OPTARG"
			;;
		f)
			readonly FORCE=true
			OPTS="$OPTS -f"
			;;
		r)
			OPTS="$OPTS -r"
			;;
		v)
			export GASHOPT_VERBOSE=true
			;;
		D)
			export GASHOPT_LOGLEVEL="DEBUG"
			;;
		d)
			export GASHOPT_DRYRUN=true
			;;
		c)
			export GASHOPT_COLOR=true
			;;
		t)
			export GASHOPT_TIMESTAMP=true
			;;
		V)
			echo -e "$VERSION"
			exit 0
			;;
		h)
			echo -e "$HELP"
			exit 0
			;;
		*)
			info_and_exit
			;;
	esac
done

# Remove options from $@
shift $((OPTIND-1))

##
## Arguments
##
if [[ $# -eq 1 ]]; then
	readonly COMMAND="copy"
	readonly FILEPATH="$1"
elif [[ $# -eq 2 ]]; then
	readonly COMMAND="$1"
	readonly FILEPATH="$2"
else
	echo -e "$0: Wrong number of arguments." 1>&2
	info_and_exit
fi

##
## Evaluate COMMAND
##
COPY=false
REMOVE=false
LIST=false
STATS=false
case "$COMMAND" in
	("copy"|"cp")
		COPY=true
		;;
	("remove"|"rm")
		REMOVE=true
		;;
	("copyremove"|"cprm")
		COPY=true
		REMOVE=true
		;;
	("list"|"ls")
		LIST=true
		;;
	("stats"|"st")
		STATS=true
		;;
	(*)
		echo -e "$0: Unkown command." 1>&2
		info_and_exit
		;;
esac

##
## Evaluate FILE
##
readonly FILENAMEFULL=$(basename -- "$FILEPATH")
readonly FILENAME="${FILENAMEFULL%.*}"
readonly TARGET="${GASHOPT_GR_PATH}${FILENAME}_gr"

if [[ -d $FILEPATH ]]; then
	FILEEXTENSION=""
elif [[ -f $FILEPATH ]]; then
	FILEEXTENSION=".${FILENAMEFULL##*.}"
	if [ "$FILEEXTENSION" = ".$FILENAME" ]; then
		FILEEXTENSION=""
	fi
else
	gash-echo "ERROR" "'$FILEPATH' not found."
	exit 1
fi

##
## List
##
if $LIST; then
	gash-echo "DEBUG" "======[ List ]======"
	ls_opts="-d"
	if $GASHOPT_VERBOSE; then
		ls_opts="$ls_opts -l -h"
	fi
	if $GASHOPT_COLOR; then
		ls_opts="$ls_opts --color=always"
	fi
	ls $ls_opts $TARGET*$FILEEXTENSION
	RETURN_VALUE=$?
fi

##
## Copy
##
if $COPY; then
	gash-echo "DEBUG" "======[ Copy ]======"
	gash-exec "cp $OPTS $FILEPATH $TARGET$(date +%Y%m%d%H%M%S)$FILEEXTENSION" "Writing timestamped copy of '$FILENAMEFULL'"
	RETURN_VALUE=$?
	if [[ $RETURN_VALUE -ne 0 ]] && $REMOVE; then
		gash-echo "ERROR" "Failed to write copy of '$FILENAMEFULL'"
		ask_for_continue $RETURN_VALUE
	fi
fi

##
## Remove
##
if $REMOVE; then
	gash-echo "DEBUG" "======[ Remove ]======"

	# Evaluate mode
	if ! [[ $GASHOPT_GR_MODE =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		gash-echo "ERROR" "Invalid retention mode." 1>&2
		exit 1
	fi
	readonly D=$(cut -d '.' -f1 <<< $GASHOPT_GR_MODE)
	readonly M=$(cut -d '.' -f2 <<< $GASHOPT_GR_MODE)
	readonly Y=$(cut -d '.' -f3 <<< $GASHOPT_GR_MODE)
	readonly A=$(cut -d '.' -f4 <<< $GASHOPT_GR_MODE)

	# Remove old copies
	RETAINED=0
	gash-echo "DEBUG" "## Step 1: Day   [retention limit ´$D´]"
	remove "$TARGET$(date +%Y%m%d)*$FILEEXTENSION" $D

	gash-echo "DEBUG" "## Step 2: Month [retention limit ´$M´]"
	remove "$TARGET$(date +%Y%m)*$FILEEXTENSION" $M
	
	gash-echo "DEBUG" "## Step 3: Year  [retention limit ´$Y´]"
	remove "$TARGET$(date +%Y)*$FILEEXTENSION" $Y

	gash-echo "DEBUG" "## Step 4: All   [retention limit ´$A´]"
	remove "$TARGET*$FILEEXTENSION" $A
fi

##
## Stats
##
if $STATS; then
	gash-echo "DEBUG" "======[ Stats ]======"
	readonly D=$(count "$TARGET$(date +%Y%m%d)*$FILEEXTENSION")
	readonly M=$(count "$TARGET$(date +%Y%m)*$FILEEXTENSION")
	readonly Y=$(count "$TARGET$(date +%Y)*$FILEEXTENSION")
	readonly A=$(count "$TARGET*$FILEEXTENSION")

	if $GASHOPT_VERBOSE; then
		m_minus_d=$(($M-$D))
		y_minus_dm=$(($Y-($D+$m_minus_d)))
		a_minus_dmy=$(($A-($D+$m_minus_d+$y_minus_dm)))

		output="| ; | Today; | This Month; | This year; | Overall\n"
		output="$output| ------------------------; | -----; | ----------; | ---------; | -------\n"
		output="$output| Including previous steps; | $D; | $M; | $Y; | $A\n"
		output="$output| Excluding previous steps; | $D; | $m_minus_d; | $y_minus_dm; | $a_minus_dmy\n"

		gash-echo "INFO" "Existing copies:\n\n$(echo -en "$output" | column -t -s ";" -x)\n\n"
	else
		gash-echo "INFO" "Found $A copies of '$FILENAMEFULL' ($D with todays timestamp, $M with this months, $Y with this years)."
	fi

	if [[ $A -eq 0 ]]; then
		RETURN_VALUE=1
	else
		RETURN_VALUE=0
	fi
fi

##
## Done
##
gash-echo "DEBUG" "======[ Done ]======"
exit $RETURN_VALUE
